from pydantic import BaseModel
from typing import Optional, Dict, List

class Task(BaseModel):
    """
    Represents a single task to be executed.

    A task defines a command to be run, along with its metadata, such as
        dependencies and expected inputs/outputs.

    Attributes:
        command (str): The shell command to execute for the task.
        description (Optional[str]): A human-readable description of what the task does.
        inputs (Optional[List[str]]): A list of input files or resources the task depends on.
        depends_on (Optional[List[str]]): A list of names of other tasks that must be
                                         completed before this one can run.
        outputs (Optional[List[str]]): A list of output files or resources generated by the task.
    """
    command: str
    description: Optional[str] = None
    inputs: Optional[List[str]] = None
    depends_on: Optional[List[str]] = None
    outputs: Optional[List[str]] = None

class Config(BaseModel):
    """
    Defines the top-level structure of the configuration file.

    This model acts as the root of the configuration schema, containing all
    the tasks defined for the project.

    Attributes:
        tasks (Dict[str, Task]): A dictionary mapping unique task names to their
                                 corresponding Task object definitions.
    """
    tasks: Dict[str, Task]
